Update codemagic.yaml: Generate universal APK from AAB

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -82,7 +82,7 @@ workflows:
           #!/usr/bin/env sh
           set -e # exit on first failed command
 
-          # Build the Flutter APK app
+          # Build the Flutter app
           flutter build appbundle --release \
             --flavor stage \
             -t lib/main_stage.dart \
@@ -92,6 +92,19 @@ workflows:
             --dart-define=TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN \
             --dart-define=TWILIO_NUMBER=$TWILIO_NUMBER \
             --dart-define=TWILIO_SERVICE_SID=$TWILIO_SERVICE_SID \
+        working_directory: recipients_app
+      - name: Generate universal APK from AAB
+        script: |
+          #!/usr/bin/env sh
+          set -e # exit on first failed command
+
+          android-app-bundle build-universal-apk \
+            --bundle 'recipients_app/build/**/outputs/bundle/stageRelease/**/*.aab' \
+            --ks $CM_KEYSTORE_PATH \
+            --ks-pass $CM_KEYSTORE_PASSWORD \
+            --ks-key-alias $CM_KEY_ALIAS \
+            --key-pass $CM_KEY_PASSWORD \
+            --output 'recipients_app/build/app/outputs/apk/stage/release/app-stage-release-universal.apk'
         working_directory: recipients_app
 
     artifacts:
