Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -62,6 +62,16 @@ workflows:
           keyAlias=$CM_KEY_ALIAS
           storeFile=$CM_KEYSTORE_PATH
           EOF
+      - name: Load Firebase configuration
+        script: |
+          #!/usr/bin/env sh
+          set -e # exit on first failed command
+
+          cd $CM_BUILD_DIR/recipients_app/android/app/src
+          mkdir stage
+          cd stage
+
+          echo $ANDROID_FIREBASE_SECRET > google-services.json
       # - name: Decode Google credentials
       #   script: |
       #     echo $FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
@@ -237,6 +247,13 @@ workflows:
         - $HOME/Library/Caches/CocoaPods
 
     scripts:
+      - name: Load Firebase configuration
+        script: |
+          #!/usr/bin/env sh
+          set -e # exit on first failed command
+
+          cd $CM_BUILD_DIR/recipients_app/ios/Runner
+          echo $IOS_FIREBASE_SECRET > GoogleService-Info.plist
       - name: Set up code signing settings on Xcode project
         script: |
           #!/usr/bin/env sh
@@ -336,6 +353,13 @@ workflows:
       #       --create
       # - name: Set up signing certificate
       #   script: keychain add-certificates
+      - name: Load Firebase configuration
+        script: |
+          #!/usr/bin/env sh
+          set -e # exit on first failed command
+
+          cd $CM_BUILD_DIR/recipients_app/ios/Runner
+          echo $IOS_FIREBASE_SECRET > GoogleService-Info.plist
       - name: Set up code signing settings on Xcode project
         script: |
           #!/usr/bin/env sh
@@ -425,13 +449,13 @@ workflows:
         - $HOME/Library/Caches/CocoaPods
 
     scripts:
-      - name: Load Prod Firebase configuration
+      - name: Load Firebase configuration
         script: |
           #!/usr/bin/env sh
           set -e # exit on first failed command
 
-          cd $CM_BUILD_DIR/recipients_app/ios/GoogleServicesConfig
-          echo $IOS_FIREBASE_SECRET > GoogleService-Info-Prod.plist
+          cd $CM_BUILD_DIR/recipients_app/ios/Runner
+          echo $IOS_FIREBASE_SECRET > GoogleService-Info.plist
       - name: Set up code signing settings on Xcode project
         script: |
           #!/usr/bin/env sh
