feat: enhance error handling and update Dockerfile for GCP deployment

diff --git a/website/Dockerfile b/website/Dockerfile
--- a/website/Dockerfile
+++ b/website/Dockerfile
@@ -31,23 +31,17 @@ FROM base AS deps
 RUN apk add --no-cache libc6-compat
 
 COPY . .
-
 RUN npm ci
 
 # -------- Build Layer --------
 FROM base AS builder
-WORKDIR /app/website
+WORKDIR /app
 
-COPY --from=deps /app/node_modules ../node_modules
-COPY --from=deps /app/website ./
-COPY --from=deps /app/shared ../shared
-COPY --from=deps /app/ui ../ui
-COPY --from=deps /app/recipients_selection ../recipients_selection
-COPY --from=base /app/.env /app/.env
+COPY --from=deps /app /app
 
 RUN set -a && . /app/.env && set +a && \
-    npx prisma generate --schema=../shared/src/database/schema.prisma && \
-    npm run build --loglevel verbose || (echo "🚨 Build failed. Printing log:" && cat /root/.npm/_logs/*-debug-0.log && false)
+    npx prisma generate --schema=shared/src/database/schema.prisma && \
+    npm --workspace=@socialincome/website run build --loglevel verbose || (echo "🚨 Build failed. Printing log:" && cat /root/.npm/_logs/*-debug-0.log && false)
 
 # -------- Runtime Layer --------
 FROM node:22-alpine AS runner
@@ -61,12 +55,9 @@ RUN addgroup --system --gid 1001 nodejs && \
 
 COPY --from=builder /app/website/public ./public
 COPY --from=builder /app/node_modules ./node_modules
-COPY --from=builder /app/recipients_selection ./recipients_selection
-COPY --from=builder /app/website/.next/standalone ./
-COPY --from=builder /app/website/.next/static ./.next/static
-COPY --from=builder /app/shared ./shared
+COPY --from=builder /app /app
 COPY --from=base /app/.env .env
 
 USER nextjs
 
-CMD ["sh", "-c", "set -a && . .env && set +a && npx prisma migrate deploy --schema=./shared/src/database/schema.prisma && node server.js"]
+CMD ["sh", "-c", "set -a && . .env && set +a && npx prisma migrate deploy --schema=./shared/src/database/schema.prisma && node website/.next/standalone/server.js"]
